name: aavinposfro
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  printing: ^5.9.1
  firebase_core: ^1.13.1
  firebase_analytics: ^9.1.2
  firebase_auth: ^3.3.9
  firebase_crashlytics: ^2.7.2
  cloud_firestore: ^3.1.10
  date_format: ^2.0.5
  path_provider: ^2.0.1
  open_file: ^3.1.0
  animated_text_kit: ^4.2.1
  shared_preferences: ^2.0.6
  flutter_redux: ^0.9.0
  redux: ^5.0.0
  redux_logging: ^0.5.0
  quiver: ^3.0.1+1
  cached_network_image: ^3.2.0
  syncfusion_flutter_pdf: ^19.1.55-beta
  pdf: ^3.8.1



  validators: ^3.0.0

  # Google Fonts Dependency
  google_fonts: ^2.3.1
  # Date Formatter Dependency
  intl: ^0.17.0
  # Relative Time Dependency
  timeago: ^3.2.2

  #Http
  http: any

  flutter_barcode_scanner: ^2.0.0
  #  audioplayers: any
  audioplayers: ^0.20.1
  flutter_svg: ^1.0.3
  date_time_picker: ^2.1.0
  lottie: ^1.0.0
  animations: ^2.0.7




  uuid: ^3.0.6




dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  image_path: "assets/aavin_logo_xl.png"
  # image_path_android: "assets/images/appstore.png"
  # image_path_ios: "assets/images/appstore.png"
  android: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - .DS_Store

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
